from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from bookforge.contracts import (
    CapabilityDescriptor,
    CapabilityEvidenceSource,
    CapabilityProjection,
    CapabilityRefusalSemantics,
    ScopeSelector,
)

from .actions import list_execution_options


def _evidence(source_type: str, reference: str, note: Optional[str] = None) -> CapabilityEvidenceSource:
    return CapabilityEvidenceSource(source_type=source_type, reference=reference, note=note)


def _refusal(mode: str, *codes: str, message: Optional[str] = None) -> CapabilityRefusalSemantics:
    return CapabilityRefusalSemantics(
        refusal_mode=mode,
        refusal_reason_codes=[code for code in codes if code],
        human_message=message,
    )


def _infer_process_area(key: str, workflow_family: Optional[str] = None) -> str:
    key = str(key or "")
    if workflow_family == "recovery_import" or "recovery" in key or key in {"quarantine_artifacts", "normalize_outline_scope", "invalidate_scope_outputs", "rebuild_state_scope", "redraft_scope"}:
        return "recovery"
    if "outline" in key or workflow_family in {"deep_outline", "thin_outline", "section_local_outline"} or "section_lineage" in key:
        return "outline"
    if "branch" in key or "assembly" in key or "fork" in key:
        return "branching"
    if "appearance" in key or "setting" in key or "context_projection" in key or "thought_context" in key:
        return "projection_layers"
    if "reader" in key or "manuscript" in key or "compile" in key or "export" in key:
        return "reader_output"
    if "author" in key:
        return "author_assets"
    if "visual" in key or "image" in key or "background_layer" in key or "character_reference" in key:
        return "visual_assets"
    if "intent" in key or "synopsis" in key or "book_seed" in key:
        return "book_intent"
    if "scene" in key or "write" in key or "lint" in key or "repair" in key or "chapter" in key or workflow_family == "section_write":
        return "writing"
    if "integrity" in key or "continuity" in key or "workflow" in key or "workspace" in key:
        return "diagnostics"
    return "engine"


def _action_spec(
    action_key: str,
    label: str,
    *,
    unit_type: str = "primitive_action",
    capability_type: str = "action",
    scopes: Iterable[str],
    selector_shape: Iterable[str],
    branch_policy: str,
    mutation_class: str,
    workflow_family: Optional[str] = None,
    approval_required: bool = False,
    readiness_source: Optional[str] = "list_execution_options",
    expected_receipt_type: str = "execution_result_v1",
    artifact_statuses: Iterable[str] = (),
    relationships: Iterable[str] = (),
    child_actions: Iterable[str] = (),
    process_area: Optional[str] = None,
    details: Optional[Dict[str, Any]] = None,
) -> CapabilityDescriptor:
    merged_details = dict(details or {})
    if workflow_family:
        merged_details["workflow_family"] = workflow_family
    return CapabilityDescriptor(
        capability_id=f"action.{action_key}",
        human_label=label,
        unit_type=unit_type,
        capability_type=capability_type,
        action_key=action_key,
        supported_scope_kinds=list(scopes),
        required_selector_shape=list(selector_shape),
        branch_policy=branch_policy,
        mutation_class=mutation_class,
        approval_required=approval_required,
        readiness_source=readiness_source,
        expected_receipt_type=expected_receipt_type,
        process_area=process_area or _infer_process_area(action_key, workflow_family),
        produced_artifact_statuses=list(artifact_statuses),
        legal_next_action_relationships=list(relationships),
        child_actions=list(child_actions),
        refusal_semantics=_refusal("dynamic_readiness_refusal", "not_ready", "scope_mismatch", "lineage_blocked"),
        evidence_sources=[
            _evidence("function", "bookforge.query.actions:list_execution_options"),
            _evidence("cli", "bookforge workflow legal-actions"),
        ],
        details=merged_details,
    )


def _query_spec(
    query_key: str,
    label: str,
    *,
    scopes: Iterable[str],
    selector_shape: Iterable[str],
    artifact_statuses: Iterable[str] = ("diagnostic",),
    evidence: str,
    process_area: Optional[str] = None,
    details: Optional[Dict[str, Any]] = None,
) -> CapabilityDescriptor:
    return CapabilityDescriptor(
        capability_id=f"query.{query_key}",
        human_label=label,
        unit_type="query",
        capability_type="query",
        query_key=query_key,
        supported_scope_kinds=list(scopes),
        required_selector_shape=list(selector_shape),
        branch_policy="any",
        mutation_class="read_only",
        approval_required=False,
        readiness_source=None,
        expected_receipt_type="query_result",
        process_area=process_area or _infer_process_area(query_key),
        produced_artifact_statuses=list(artifact_statuses),
        refusal_semantics=_refusal("query_refusal", "missing_scope", "missing_artifact"),
        evidence_sources=[_evidence("function", evidence)],
        details=dict(details or {}),
    )


def _readiness_spec(
    query_key: str,
    label: str,
    *,
    scopes: Iterable[str],
    selector_shape: Iterable[str],
    evidence: str,
    process_area: Optional[str] = None,
) -> CapabilityDescriptor:
    return CapabilityDescriptor(
        capability_id=f"readiness.{query_key}",
        human_label=label,
        unit_type="readiness",
        capability_type="readiness",
        query_key=query_key,
        supported_scope_kinds=list(scopes),
        required_selector_shape=list(selector_shape),
        branch_policy="any",
        mutation_class="read_only",
        approval_required=False,
        readiness_source=query_key,
        expected_receipt_type="readiness_result",
        process_area=process_area or _infer_process_area(query_key),
        produced_artifact_statuses=["diagnostic"],
        refusal_semantics=_refusal("readiness_refusal", "missing_prerequisite", "scope_mismatch", "artifact_missing"),
        evidence_sources=[_evidence("function", evidence)],
    )


def _gap_spec(
    capability_id: str,
    label: str,
    *,
    unit_type: str,
    capability_type: str,
    scopes: Iterable[str],
    selector_shape: Iterable[str],
    mutation_class: str = "read_only",
    branch_policy: str = "any",
    process_area: Optional[str] = None,
    details: Optional[Dict[str, Any]] = None,
) -> CapabilityDescriptor:
    return CapabilityDescriptor(
        capability_id=capability_id,
        human_label=label,
        unit_type=unit_type,
        capability_type=capability_type,
        implementation_status="designed_gap",
        supported_scope_kinds=list(scopes),
        required_selector_shape=list(selector_shape),
        branch_policy=branch_policy,
        mutation_class=mutation_class,
        approval_required=True,
        expected_receipt_type=None,
        process_area=process_area or _infer_process_area(capability_id),
        produced_artifact_statuses=[],
        refusal_semantics=_refusal(
            "not_implemented",
            "designed_gap",
            message="This capability is intentionally surfaced as a planned gap, not an executable BookForge action.",
        ),
        evidence_sources=[_evidence("plan", "resources/plans/InProgress/bookforge-action-skill-projection-for-nanda")],
        details=dict(details or {}),
    )


ACTION_CAPABILITY_SPECS: Dict[str, CapabilityDescriptor] = {
    "plan_visual_asset": _action_spec(
        "plan_visual_asset",
        "Plan a visual asset prompt package",
        unit_type="primitive_action",
        capability_type="action",
        scopes=["book", "author", "branch", "scene"],
        selector_shape=["book_id", "details.prompt_text"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="visual_assets",
        readiness_source="visual_action_readiness",
        expected_receipt_type="execution_result_v1",
        artifact_statuses=["provisional"],
        process_area="visual_assets",
        relationships=["enables_visual_generation"],
        details={
            "default_provider_model": "nano-banana",
            "default_model_id": "gemini-2.5-flash-image",
            "option_provider_models": ["nano-banana", "gpt-image-2", "dall-e-3", "grok-imagine-image"],
        },
    ),
    "generate_visual_asset": _action_spec(
        "generate_visual_asset",
        "Generate a visual asset from a prompt plan",
        unit_type="primitive_action",
        capability_type="action",
        scopes=["book", "author", "branch", "scene"],
        selector_shape=["book_id", "details.prompt_plan_path", "details.allow_spend"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="visual_assets",
        approval_required=True,
        readiness_source="visual_action_readiness",
        expected_receipt_type="execution_result_v1",
        artifact_statuses=["provisional", "diagnostic"],
        process_area="visual_assets",
        relationships=["requires_plan_visual_asset"],
        details={
            "default_provider_model": "nano-banana",
            "default_model_id": "gemini-2.5-flash-image",
            "option_provider_models": ["nano-banana", "gpt-image-2", "dall-e-3", "grok-imagine-image"],
            "spend_guard": "requires explicit allow_spend=true",
        },
    ),
    "create_author": _action_spec(
        "create_author",
        "Create a versioned author persona",
        scopes=["library", "author"],
        selector_shape=["book_id", "details.influences_or_prompt"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="author_assets",
        approval_required=True,
        artifact_statuses=["authoritative"],
        details={
            "library_scope_id": "__author_library__",
            "versioned": True,
            "writes": [
                "workspace/authors/<author_slug>/<version>/author.json",
                "workspace/authors/<author_slug>/<version>/author_style.md",
                "workspace/authors/<author_slug>/<version>/system_fragment.md",
                "workspace/authors/<author_slug>/index.json",
            ],
        },
    ),
    "refine_author": _action_spec(
        "refine_author",
        "Refine an author persona into a new version",
        scopes=["author"],
        selector_shape=["book_id", "details.author_ref", "details.instructions_or_prompt"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="author_assets",
        approval_required=True,
        artifact_statuses=["authoritative"],
        relationships=["creates_successor_author_version"],
        details={
            "library_scope_id": "__author_library__",
            "versioned": True,
            "overwrite_behavior": "creates_new_version",
        },
    ),
    "draft_book_intent": _action_spec(
        "draft_book_intent",
        "Draft a BookIntent from an author-only seed",
        scopes=["library", "book_seed", "book"],
        selector_shape=["book_id", "details.title", "details.author_ref", "details.genre", "details.seed_text_or_seed_file"],
        branch_policy="main_only",
        mutation_class="provisional_branch_mutation",
        workflow_family="book_intent",
        artifact_statuses=["provisional"],
        relationships=["enables_approve_book_intent"],
        process_area="book_intent",
        details={
            "library_scope_id": "__book_intents__",
            "canonical_book_created": False,
            "truth_note": "This formalizes an author-only seed; it does not create a canonical book workspace.",
        },
    ),
    "approve_book_intent": _action_spec(
        "approve_book_intent",
        "Approve a BookIntent for canonical book creation",
        scopes=["book_seed", "book"],
        selector_shape=["book_id", "details.intent_ref"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="book_intent",
        approval_required=True,
        artifact_statuses=["authoritative"],
        relationships=["enables_create_book_from_intent"],
        process_area="book_intent",
        details={
            "library_scope_id": "__book_intents__",
            "approval_meaning": "The seed, title, author, genre, and intent fields are accepted as the source for a new BookForge book.",
        },
    ),
    "create_book_from_intent": _action_spec(
        "create_book_from_intent",
        "Create a canonical BookForge book from an approved BookIntent",
        scopes=["book_seed", "book"],
        selector_shape=["book_id", "details.intent_ref"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="book_intent",
        approval_required=True,
        artifact_statuses=["authoritative"],
        relationships=["creates_book_workspace"],
        process_area="book_intent",
        details={
            "library_scope_id": "__book_intents__",
            "canonical_transition": "author_only_seed_to_book_scope",
            "writes": [
                "workspace/books/<book_id>/book.json",
                "workspace/books/<book_id>/book_intent.json",
                "workspace/books/<book_id>/draft/context/book_intent.md",
                "workspace/books/<book_id>/prompts/system_v1.md",
            ],
        },
    ),
    "draft_starter_outline_from_intent": _action_spec(
        "draft_starter_outline_from_intent",
        "Author thin starter outline artifacts from a created BookIntent",
        scopes=["book"],
        selector_shape=["book_id"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="thin_outline",
        approval_required=True,
        artifact_statuses=["authoritative", "diagnostic"],
        relationships=["enables_initialize_section_workflow"],
        process_area="outline",
        details={
            "source": "book_intent",
            "provider_used": True,
            "provider_call_count_per_request": 1,
            "calls_outline_provider": True,
            "deep_outline_pipeline": False,
            "starter_not_deep_outline": True,
            "purpose": "Create enough authored outline shape for workflow init and adaptive scene traversal without running the full deep outline pipeline.",
            "does_not_initialize_workflow": True,
            "does_not_freeze_section": True,
            "does_not_create_branch": True,
            "does_not_write_prose": True,
            "writes": [
                "workspace/books/<book_id>/outline/pipeline_runs/<run_id>/outline_spine_v1.json",
                "workspace/books/<book_id>/outline/pipeline_runs/<run_id>/outline_sections_v1.json",
                "workspace/books/<book_id>/outline/pipeline_runs/<run_id>/outline_final_v1_1.json",
                "workspace/books/<book_id>/outline/pipeline_runs/<run_id>/outline_pipeline_report.json",
                "workspace/books/<book_id>/outline/pipeline_latest.json",
            ],
            "next_recommended_action": "initialize_section_workflow",
            "follow_on_sequence": [
                "initialize_section_workflow",
                "freeze_section_from_phase03_artifact",
                "create_branch",
                "continue_scene",
            ],
            "follow_on_sequence_policy": "Informational only; callers must re-query legal actions and readiness before every follow-on step.",
        },
    ),
    "initialize_section_workflow": _action_spec(
        "initialize_section_workflow",
        "Initialize section-local workflow state",
        scopes=["book"],
        selector_shape=["book_id"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="section_local_outline",
        approval_required=True,
        artifact_statuses=["authoritative", "derived"],
        details={
            "does_not_call_provider": True,
            "does_not_freeze_section": True,
            "does_not_create_branch": True,
            "does_not_write_prose": True,
            "next_recommended_action": "freeze_section_from_phase03_artifact",
        },
    ),
    "freeze_section_from_phase03_artifact": _action_spec(
        "freeze_section_from_phase03_artifact",
        "Freeze one section from a phase-03 outline artifact",
        scopes=["section"],
        selector_shape=["book_id", "chapter", "section"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="section_local_outline",
        approval_required=True,
        artifact_statuses=["authoritative", "derived"],
        details={
            "does_not_call_provider": True,
            "freezes_one_section_only": True,
            "does_not_create_branch": True,
            "does_not_write_prose": True,
            "next_recommended_action": "create_branch",
        },
    ),
    "write_frozen_section": _action_spec(
        "write_frozen_section",
        "Write a frozen section as a macro workflow",
        unit_type="macro_workflow",
        capability_type="macro",
        scopes=["section", "branch"],
        selector_shape=["book_id", "chapter", "section"],
        branch_policy="any",
        mutation_class="canonical_mutation",
        workflow_family="section_write",
        approval_required=True,
        artifact_statuses=["provisional", "authoritative"],
        child_actions=[
            "plan_scene",
            "preflight_scene_state",
            "generate_continuity_pack",
            "write_scene_prose",
            "state_repair_scene_patch",
            "lint_scene_prose",
            "repair_scene_prose",
            "apply_scene_commit",
        ],
        details={
            "approval_class": "section_macro",
            "macro_not_rail": True,
            "broad_macro": True,
            "preferred_single_scene_action": "continue_scene",
            "not_for_single_scene_requests": True,
            "runs_until": "selected frozen section terminal scene",
            "step_count_per_call": "all missing scenes in the selected frozen section",
            "may_execute_multiple_scene_phase_children": True,
            "refresh_required_before_invocation": True,
            "branch_local_when_branch_id_is_derived": True,
            "canonical_change_requires_main": True,
            "truth_note": (
                "This is a compatibility section macro around runner.run_section_range. "
                "It may plan, write, repair, lint, and commit every missing scene in the selected frozen section. "
                "Use continue_scene for adaptive one-step scene traversal."
            ),
        },
    ),
    "continue_scene": _action_spec(
        "continue_scene",
        "Continue one scene by executing the current recommended scene-phase action",
        unit_type="macro_workflow",
        capability_type="macro",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional", "derived", "authoritative", "diagnostic"],
        child_actions=[
            "plan_scene",
            "preflight_scene_state",
            "generate_continuity_pack",
            "write_scene_prose",
            "state_repair_scene_patch",
            "lint_scene_prose",
            "repair_scene_prose",
            "apply_scene_commit",
        ],
        relationships=["uses_scene_phase_readiness_recommended_next_action"],
        details={
            "macro_not_rail": True,
            "step_count_per_call": 1,
            "loop_step_receipt_schema": "author_loop_step_receipt_v1",
            "truth_note": "This executes only the currently recommended scene-phase child action, then returns updated readiness context.",
        },
    ),
    "align_scene_pair_seam": _action_spec(
        "align_scene_pair_seam",
        "Align one adjacent scene seam inside a branch",
        unit_type="primitive_action",
        capability_type="action",
        scopes=["scene_pair", "chapter", "branch"],
        selector_shape=["book_id", "branch_id", "chapter", "scene"],
        branch_policy="derived_only",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["authoritative", "derived", "diagnostic"],
        relationships=["uses_chapter_seam_lint_repair_pair"],
        details={
            "pair_selector_rule": "selector.scene is scene A; details.scene_b_id or outline adjacency resolves scene B",
            "writable_window_policy": "only scene A tail and scene B head are rewritten",
            "canonical_changed": False,
        },
    ),
    "plan_bridge_scene_insertion": _action_spec(
        "plan_bridge_scene_insertion",
        "Plan an adaptive bridge scene insertion",
        unit_type="primitive_action",
        capability_type="action",
        scopes=["scene_pair", "chapter", "branch"],
        selector_shape=["book_id", "branch_id", "chapter", "scene"],
        branch_policy="derived_only",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
        relationships=["precedes_apply_bridge_scene_insertion"],
        details={
            "proposal_only": True,
            "does_not_modify_outline_or_prose": True,
            "followup_action": "apply_bridge_scene_insertion",
        },
    ),
    "apply_bridge_scene_insertion": _action_spec(
        "apply_bridge_scene_insertion",
        "Apply a planned adaptive bridge scene insertion",
        unit_type="primitive_action",
        capability_type="action",
        scopes=["scene_pair", "section", "chapter", "branch"],
        selector_shape=["book_id", "branch_id", "chapter", "scene"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["authoritative", "diagnostic"],
        relationships=["requires_plan_bridge_scene_insertion", "enables_plan_scene_for_inserted_scene"],
        details={
            "branch_only": True,
            "renumbering_policy": "branch_local_shift_following_integer_scene_ids",
            "same_section_only_first_slice": True,
            "does_not_write_bridge_prose": True,
            "canonical_changed": False,
            "nanda_wire_recommendation": "safe_to_wire_behind_gates",
            "success_receipt_schema": "execution_result_v1",
            "apply_report_schema": "bridge_scene_insertion_apply_report_v1",
            "expected_success_details": [
                "inserted_scene_id",
                "branch_id",
                "canonical_changed",
                "branch_change_status",
                "recommended_next_actions",
            ],
            "expected_artifact_keys": [
                "bridge_scene_insertion_apply_report",
                "outline",
                "snapshot_registry",
            ],
            "legal_details_fields": [
                "chapter_id",
                "scene_a_id",
                "scene_b_id",
                "mutation_scope",
                "artifact_status_after_success",
                "canonical_changed",
                "renumbering_policy",
                "same_section_only",
                "bridge_plan_path",
                "refusal_code",
            ],
            "legal_refusal_codes": [
                "branch_required",
                "missing_chapter_or_scene_scope",
                "no_adjacent_scene",
                "missing_bridge_scene_insertion_plan",
            ],
            "execution_failure_codes": [
                "branch_required",
                "missing_live_node",
                "stale_write",
                "scope_contract_violation",
                "bridge_scene_insertion_apply_failed",
            ],
        },
    ),
    "lock_section_from_written_state": _action_spec(
        "lock_section_from_written_state",
        "Lock a written section",
        scopes=["section"],
        selector_shape=["book_id", "chapter", "section"],
        branch_policy="any",
        mutation_class="branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["authoritative"],
        details={
            "dynamic_mutation_scope": "canonical on main; branch_authoritative on derived branches",
            "canonical_change_requires_main": True,
        },
    ),
    "finalize_chapter_from_locked_sections": _action_spec(
        "finalize_chapter_from_locked_sections",
        "Finalize a chapter from locked sections",
        unit_type="macro_workflow",
        capability_type="macro",
        scopes=["chapter"],
        selector_shape=["book_id", "chapter"],
        branch_policy="any",
        mutation_class="branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["authoritative", "diagnostic"],
        child_actions=["pairwise_scene_seam_repair", "chapter_seam_audit"],
        details={
            "child_actions_include_internal_unprojected_work": True,
            "dynamic_mutation_scope": "canonical on main; branch_authoritative on derived branches",
            "canonical_change_requires_main": True,
        },
    ),
    "resume_paused_section": _action_spec(
        "resume_paused_section",
        "Resume a paused main-branch section",
        scopes=["book", "section"],
        selector_shape=["book_id"],
        branch_policy="main_only",
        mutation_class="canonical_mutation",
        workflow_family="section_write",
        artifact_statuses=["authoritative", "provisional", "diagnostic"],
    ),
    "create_branch": _action_spec(
        "create_branch",
        "Create an isolated derived branch",
        scopes=["book", "chapter", "section", "scene", "branch"],
        selector_shape=["book_id"],
        branch_policy="main_only",
        mutation_class="branch_mutation",
        artifact_statuses=["diagnostic"],
        relationships=["branch_scope_unlocks_branch_local_actions"],
    ),
    "create_recovery_branch": _action_spec(
        "create_recovery_branch",
        "Create isolated recovery branch and record anchor",
        scopes=["book", "chapter", "section"],
        selector_shape=["book_id"],
        branch_policy="main_only",
        mutation_class="branch_mutation",
        workflow_family="recovery_import",
        approval_required=True,
        artifact_statuses=["diagnostic"],
        details={
            "cleanliness_status_after_success": "isolated_not_clean",
            "truth_note": (
                "This action isolates work and records the selected recovery anchor. "
                "It does not remove polluted data or apply the anchor by itself."
            ),
            "required_cleanup_actions": [
                "quarantine_artifacts",
                "normalize_outline_scope",
                "invalidate_scope_outputs",
                "rebuild_state_scope",
                "redraft_scope",
                "validate_recovery_branch",
            ],
        },
    ),
    "create_assembly_branch": _action_spec(
        "create_assembly_branch",
        "Create an off-main assembly branch for a fork group",
        scopes=["fork_group"],
        selector_shape=["book_id", "fork_group_id"],
        branch_policy="main_only",
        mutation_class="assembly",
        approval_required=True,
        artifact_statuses=["diagnostic"],
    ),
    "discard_branch": _action_spec(
        "discard_branch",
        "Discard a derived branch",
        scopes=["branch"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        approval_required=True,
        artifact_statuses=["diagnostic"],
    ),
    "promote_branch_to_main": _action_spec(
        "promote_branch_to_main",
        "Promote a branch to main",
        unit_type="promotion_action",
        capability_type="promotion",
        scopes=["branch"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="promotion",
        approval_required=True,
        artifact_statuses=["authoritative", "diagnostic"],
    ),
    "record_assembly_validation": _action_spec(
        "record_assembly_validation",
        "Record assembly validation result",
        unit_type="validation_gate",
        capability_type="diagnostic",
        scopes=["branch", "fork_group"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="diagnostic_only",
        artifact_statuses=["diagnostic"],
    ),
    "plan_scene": _action_spec(
        "plan_scene",
        "Plan one scene without downstream execution",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
        relationships=["enables_preflight_scene_state"],
    ),
    "preflight_scene_state": _action_spec(
        "preflight_scene_state",
        "Preflight one scene state patch",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
        relationships=["enables_generate_continuity_pack"],
    ),
    "generate_continuity_pack": _action_spec(
        "generate_continuity_pack",
        "Generate one scene continuity pack",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="diagnostic_only",
        workflow_family="section_write",
        artifact_statuses=["derived"],
        relationships=["enables_write_scene_prose"],
    ),
    "write_scene_prose": _action_spec(
        "write_scene_prose",
        "Write one scene prose artifact",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
        relationships=["enables_state_repair_scene_patch"],
    ),
    "refresh_character_appearance_projection": _action_spec(
        "refresh_character_appearance_projection",
        "Refresh character appearance projection for one scene",
        unit_type="projection_skill",
        capability_type="artifact",
        scopes=["scene", "character", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["derived", "diagnostic"],
    ),
    "draft_scene_setting_projection": _action_spec(
        "draft_scene_setting_projection",
        "Draft setting/background projection for one scene",
        unit_type="projection_skill",
        capability_type="artifact",
        scopes=["scene", "setting", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
    ),
    "extract_scene_setting_from_prose": _action_spec(
        "extract_scene_setting_from_prose",
        "Extract setting/background projection from prose",
        unit_type="projection_skill",
        capability_type="artifact",
        scopes=["scene", "setting", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["derived"],
    ),
    "state_repair_scene_patch": _action_spec(
        "state_repair_scene_patch",
        "Repair one scene state patch",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
        relationships=["enables_lint_scene_prose"],
    ),
    "lint_scene_prose": _action_spec(
        "lint_scene_prose",
        "Lint one scene prose artifact",
        unit_type="validation_gate",
        capability_type="diagnostic",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="diagnostic_only",
        workflow_family="section_write",
        artifact_statuses=["diagnostic"],
        relationships=["enables_apply_scene_commit_or_repair_scene_prose"],
    ),
    "repair_scene_prose": _action_spec(
        "repair_scene_prose",
        "Repair one scene prose artifact",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="provisional_branch_mutation",
        workflow_family="section_write",
        artifact_statuses=["provisional"],
        relationships=["returns_to_state_repair_scene_patch"],
    ),
    "apply_scene_commit": _action_spec(
        "apply_scene_commit",
        "Commit one scene baseline",
        unit_type="promotion_action",
        capability_type="promotion",
        scopes=["scene", "branch"],
        selector_shape=["book_id", "chapter", "scene"],
        branch_policy="any",
        mutation_class="canonical_mutation",
        workflow_family="section_write",
        artifact_statuses=["authoritative", "diagnostic"],
    ),
    "quarantine_artifacts": _action_spec(
        "quarantine_artifacts",
        "Quarantine stale recovery artifacts",
        scopes=["branch", "recovery_candidate"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        workflow_family="recovery_import",
        approval_required=True,
        artifact_statuses=["diagnostic"],
    ),
    "normalize_outline_scope": _action_spec(
        "normalize_outline_scope",
        "Normalize affected outline scope in a recovery branch",
        scopes=["branch", "chapter", "section"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        workflow_family="recovery_import",
        approval_required=True,
        artifact_statuses=["authoritative", "derived", "diagnostic"],
    ),
    "invalidate_scope_outputs": _action_spec(
        "invalidate_scope_outputs",
        "Invalidate generated outputs for affected recovery scope",
        scopes=["branch", "chapter", "section", "scene"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        workflow_family="recovery_import",
        approval_required=True,
        artifact_statuses=["diagnostic"],
    ),
    "rebuild_state_scope": _action_spec(
        "rebuild_state_scope",
        "Rebuild branch-local state and projections",
        scopes=["branch", "chapter", "section"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        workflow_family="recovery_import",
        artifact_statuses=["derived", "diagnostic"],
    ),
    "redraft_scope": _action_spec(
        "redraft_scope",
        "Redraft affected recovery scope",
        unit_type="macro_workflow",
        capability_type="macro",
        scopes=["branch", "chapter", "section", "scene"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="branch_mutation",
        workflow_family="recovery_import",
        approval_required=True,
        artifact_statuses=["provisional", "authoritative", "diagnostic"],
        child_actions=["write_frozen_section", "plan_scene", "write_scene_prose", "lint_scene_prose", "apply_scene_commit"],
    ),
    "validate_recovery_branch": _action_spec(
        "validate_recovery_branch",
        "Validate recovery branch health",
        unit_type="validation_gate",
        capability_type="diagnostic",
        scopes=["branch"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="diagnostic_only",
        workflow_family="recovery_import",
        artifact_statuses=["diagnostic"],
    ),
    "review_recovery_semantics": _action_spec(
        "review_recovery_semantics",
        "Review recovery semantic health",
        unit_type="validation_gate",
        capability_type="diagnostic",
        scopes=["branch"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="diagnostic_only",
        workflow_family="recovery_import",
        artifact_statuses=["diagnostic"],
    ),
    "review_downstream_dependencies": _action_spec(
        "review_downstream_dependencies",
        "Review downstream recovery dependencies",
        unit_type="validation_gate",
        capability_type="diagnostic",
        scopes=["branch"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="diagnostic_only",
        workflow_family="recovery_import",
        artifact_statuses=["diagnostic"],
    ),
    "promote_recovery_branch": _action_spec(
        "promote_recovery_branch",
        "Promote a validated recovery branch with removals",
        unit_type="promotion_action",
        capability_type="promotion",
        scopes=["branch"],
        selector_shape=["book_id", "branch_id"],
        branch_policy="derived_only",
        mutation_class="promotion",
        workflow_family="recovery_import",
        approval_required=True,
        artifact_statuses=["authoritative", "diagnostic"],
    ),
}


QUERY_CAPABILITY_SPECS: List[CapabilityDescriptor] = [
    _query_spec("author_profiles", "Author profile library", scopes=["library", "author", "book"], selector_shape=[], artifact_statuses=["authoritative"], evidence="bookforge.query.authors:list_author_profiles", process_area="author_assets"),
    _query_spec("author_profile", "Rich author voice and style profile", scopes=["author", "book"], selector_shape=["author_ref"], artifact_statuses=["authoritative"], evidence="bookforge.query.authors:get_author_profile", process_area="author_assets"),
    _query_spec("book_intents", "Book intent library", scopes=["library", "book_seed", "book"], selector_shape=[], artifact_statuses=["provisional", "authoritative"], evidence="bookforge.query.book_intent:list_book_intents", process_area="book_intent"),
    _query_spec("book_intent", "Versioned book intent and synopsis surface", scopes=["book_seed", "book"], selector_shape=["intent_ref"], artifact_statuses=["provisional", "authoritative"], evidence="bookforge.query.book_intent:get_book_intent", process_area="book_intent"),
    _query_spec("book_cards", "Book library card index", scopes=["library", "book"], selector_shape=[], evidence="bookforge.query.books:list_book_cards"),
    _query_spec("workspace_status", "Workspace status", scopes=["book", "branch"], selector_shape=["book_id"], evidence="bookforge.query.workspace:get_workspace_status"),
    _query_spec("workflow_snapshot", "Workflow snapshot", scopes=["book", "branch"], selector_shape=["book_id"], evidence="bookforge.query.workflow:get_workflow_snapshot"),
    _query_spec("next_writing_target", "Next writing target", scopes=["book", "branch", "chapter", "section", "scene"], selector_shape=["book_id"], evidence="bookforge.query.writing:get_next_writing_target", process_area="writing"),
    _query_spec(
        "writing_bootstrap_status",
        "Writing bootstrap status",
        scopes=["book", "branch", "chapter", "section", "scene"],
        selector_shape=["book_id"],
        evidence="bookforge.query.writing_bootstrap:get_writing_bootstrap_status",
        process_area="writing",
        details={
            "truth_note": "Read-only bridge from created BookIntent to branch-local writing. It reports the next valid setup or writing action without calling providers or mutating artifacts.",
            "expected_sequence": [
                "draft_starter_outline_from_intent",
                "initialize_section_workflow",
                "freeze_section_from_phase03_artifact",
                "create_branch",
                "continue_scene",
            ],
            "integrity_policy": "Blocks writing bootstrap on chimera_risk and points callers to lineage/recovery diagnostics.",
        },
    ),
    _query_spec(
        "author_loop_envelopes",
        "Author work loop envelopes",
        scopes=["book", "branch", "chapter", "section", "scene"],
        selector_shape=["book_id"],
        evidence="bookforge.query.author_loop:get_author_loop_envelopes",
        process_area="writing",
        details={
            "static_dynamic_boundary": "Envelope support must be paired with readiness/legal action queries before execution.",
            "refresh_required_between_steps": True,
            "refresh_query_order": [
                "branch_detail",
                "branch_artifact_index",
                "branch_diff_summary",
                "book_reader_scene",
                "next_writing_target",
                "writing_gate_status",
                "scene_phase_readiness",
                "legal_actions",
            ],
            "cancellation_policy": "Cancel stops scheduling new child actions; branch-local artifacts from completed child actions remain.",
        },
    ),
    _query_spec(
        "chapter_seam_queue",
        "Chapter scene-pair seam queue",
        scopes=["chapter", "scene_pair", "branch"],
        selector_shape=["book_id", "chapter"],
        evidence="bookforge.query.seams:get_chapter_seam_queue",
        process_area="writing",
        details={
            "truth_note": "Lists adjacent outline scene pairs and reports whether pairwise seam alignment is ready, blocked, or already aligned for the selected branch.",
            "action_bridge": "Ready items map to action.align_scene_pair_seam.",
        },
    ),
    _query_spec(
        "scene_pair_seam_detail",
        "Scene-pair seam report detail",
        scopes=["scene_pair", "chapter", "branch"],
        selector_shape=["book_id", "chapter", "details.scene_a_id", "details.scene_b_id"],
        evidence="bookforge.query.seams:get_scene_pair_seam_detail",
        process_area="writing",
        details={
            "truth_note": "Shows focused readiness/report evidence for one adjacent scene pair without mutating prose.",
            "report_policy": "Can include the full pair seam report payload or a summary-only projection.",
        },
    ),
    _query_spec("branch_inventory", "Branch and fork-group inventory", scopes=["book", "branch", "fork_group"], selector_shape=["book_id"], evidence="bookforge.query.branches:get_branch_inventory"),
    _query_spec("branch_detail", "Branch workbench detail view", scopes=["branch", "chapter", "section", "scene"], selector_shape=["book_id", "branch_id"], artifact_statuses=["diagnostic", "authoritative", "provisional", "derived"], evidence="bookforge.query.branches:get_branch_detail"),
    _query_spec("branch_artifact_index", "Branch artifact index", scopes=["branch"], selector_shape=["book_id", "branch_id"], artifact_statuses=["diagnostic", "authoritative", "provisional", "derived"], evidence="bookforge.query.branches:get_branch_artifact_index"),
    _query_spec("branch_diff_summary", "Branch diff summary", scopes=["branch"], selector_shape=["book_id", "branch_id"], artifact_statuses=["diagnostic", "authoritative", "provisional", "derived"], evidence="bookforge.query.branches:get_branch_diff_summary"),
    _query_spec("book_reader_index", "Canonical reader index", scopes=["book", "chapter", "section", "scene"], selector_shape=["book_id"], artifact_statuses=["authoritative", "diagnostic"], evidence="bookforge.query.reader:get_book_reader_index"),
    _query_spec("book_reader_chapter", "Canonical reader chapter view", scopes=["chapter"], selector_shape=["book_id", "chapter"], artifact_statuses=["authoritative", "diagnostic"], evidence="bookforge.query.reader:get_book_reader_chapter"),
    _query_spec("book_reader_scene", "Canonical reader scene view", scopes=["scene"], selector_shape=["book_id", "chapter", "scene"], artifact_statuses=["authoritative", "diagnostic"], evidence="bookforge.query.reader:get_book_reader_scene"),
    _query_spec(
        "book_reader_anchor",
        "Mutation-safe prose selection anchor",
        scopes=["chapter", "scene", "branch"],
        selector_shape=["book_id", "chapter", "scene", "details.start_offset", "details.end_offset"],
        artifact_statuses=["authoritative", "diagnostic"],
        evidence="bookforge.query.reader:get_book_reader_anchor",
        process_area="reader_output",
        details={
            "truth_note": "A reader anchor proves source path, hashes, selected span, branch scope, and whether the selection is safe to use as a mutation target.",
            "mutation_note": "Scene anchors can target branch-local rewrite tools. Chapter anchors are inspect-only until narrowed to a scene.",
        },
    ),
    _query_spec("integrity_verdict", "Integrity verdict", scopes=["book"], selector_shape=["book_id"], evidence="bookforge.query.integrity:get_integrity_verdict"),
    _query_spec("outline_lineage_audit", "Outline lineage audit", scopes=["book", "chapter", "section"], selector_shape=["book_id"], evidence="bookforge.query.outline_lineage:get_outline_lineage_audit"),
    _query_spec("section_lineage_matrix", "Section lineage matrix", scopes=["book", "chapter", "section"], selector_shape=["book_id"], evidence="bookforge.query.outline_lineage:get_section_lineage_matrix"),
    _query_spec("stale_outline_artifact_inventory", "Stale outline artifact inventory", scopes=["book"], selector_shape=["book_id"], evidence="bookforge.query.outline_lineage:get_stale_outline_artifact_inventory"),
    _query_spec("outline_repair_candidates", "Outline repair candidates", scopes=["book", "chapter", "section"], selector_shape=["book_id"], evidence="bookforge.query.outline_lineage:get_outline_repair_candidates"),
    _query_spec("recovery_anchor_candidates", "Recovery anchor candidates", scopes=["book", "chapter", "section"], selector_shape=["book_id"], evidence="bookforge.query.recovery:get_recovery_anchor_candidates"),
    _query_spec("recovery_plan_preview", "Recovery plan preview", scopes=["book", "chapter", "section"], selector_shape=["book_id"], evidence="bookforge.query.recovery:get_recovery_plan_preview"),
    _query_spec("recovery_branch_health", "Recovery branch health", scopes=["branch"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_recovery_branch_health"),
    _query_spec("recovery_blast_radius", "Recovery blast radius", scopes=["branch", "chapter", "section"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_recovery_blast_radius"),
    _query_spec("scope_invalidation_preview", "Scope invalidation preview", scopes=["branch", "chapter", "section", "scene"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_scope_invalidation_preview"),
    _query_spec("state_rebuild_preview", "State rebuild preview", scopes=["branch", "chapter", "section"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_state_rebuild_preview"),
    _query_spec("salvage_candidates", "Salvage candidates", scopes=["branch", "chapter", "section", "scene"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_salvage_candidates"),
    _query_spec("character_views", "Character projection views", scopes=["book", "chapter", "section", "scene", "character"], selector_shape=["book_id"], artifact_statuses=["derived"], evidence="bookforge.query.characters:list_character_views"),
    _query_spec("continuity_view", "Continuity projection view", scopes=["book", "chapter", "section", "scene"], selector_shape=["book_id"], artifact_statuses=["derived"], evidence="bookforge.query.continuity:get_continuity_view"),
    _query_spec("appearance_projection_views", "Appearance projection views", scopes=["book", "chapter", "section", "scene", "character"], selector_shape=["book_id"], artifact_statuses=["derived"], evidence="bookforge.query.appearance:list_appearance_projection_views"),
    _query_spec("scene_setting_projection", "Scene setting projection", scopes=["scene", "setting"], selector_shape=["book_id", "chapter", "scene"], artifact_statuses=["derived", "provisional"], evidence="bookforge.query.setting:get_scene_setting_projection"),
    _query_spec("scene_context_projection", "Scene context projection", scopes=["scene"], selector_shape=["book_id", "chapter", "scene"], artifact_statuses=["derived"], evidence="bookforge.query.scene_context:get_scene_context_projection"),
    _query_spec("thought_context_projection", "Thought context projection", scopes=["book", "chapter", "section", "scene"], selector_shape=["book_id"], artifact_statuses=["diagnostic"], evidence="bookforge.query.thought_context:get_thought_context_projection"),
    _query_spec("visual_provider_descriptors", "Visual provider descriptors", scopes=["library", "book", "author"], selector_shape=[], artifact_statuses=["diagnostic"], evidence="bookforge.query.visual:list_visual_provider_descriptors", process_area="visual_assets"),
    _query_spec("visual_asset_index", "Visual prompt-plan and generated-asset index", scopes=["book", "author", "branch", "scene"], selector_shape=["book_id"], artifact_statuses=["provisional", "diagnostic"], evidence="bookforge.query.visual:get_visual_asset_index", process_area="visual_assets"),
    _query_spec("visual_asset_detail", "Visual generated-asset detail with manifest and prompt-plan source", scopes=["book", "author", "branch", "scene"], selector_shape=["book_id", "details.asset_id"], artifact_statuses=["provisional", "diagnostic"], evidence="bookforge.query.visual:get_visual_asset_detail", process_area="visual_assets"),
    _query_spec("visual_prompt_plan_detail", "Visual prompt-plan detail", scopes=["book", "author", "branch", "scene"], selector_shape=["book_id", "details.prompt_plan_ref"], artifact_statuses=["provisional"], evidence="bookforge.query.visual:get_visual_prompt_plan_detail", process_area="visual_assets"),
]


READINESS_CAPABILITY_SPECS: List[CapabilityDescriptor] = [
    _readiness_spec("legal_next_actions", "Legal next actions", scopes=["book", "chapter", "section", "scene", "branch", "fork_group"], selector_shape=["book_id"], evidence="bookforge.query.actions:list_execution_options"),
    _readiness_spec("scene_phase_readiness", "Scene phase readiness", scopes=["scene", "branch"], selector_shape=["book_id", "chapter", "scene"], evidence="bookforge.query.scene_phase:get_scene_phase_readiness"),
    _readiness_spec("writing_gate_status", "Writing gate status", scopes=["book", "branch", "chapter", "section", "scene"], selector_shape=["book_id"], evidence="bookforge.query.writing:get_writing_gate_status", process_area="writing"),
    _readiness_spec("recovery_plan_readiness", "Recovery plan readiness", scopes=["branch"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_recovery_plan_readiness"),
    _readiness_spec("recovery_semantic_review_readiness", "Recovery semantic review readiness", scopes=["branch"], selector_shape=["book_id", "branch_id"], evidence="bookforge.query.recovery:get_recovery_semantic_review_readiness"),
    _readiness_spec("visual_action_readiness", "Visual action readiness", scopes=["book", "author", "branch", "scene"], selector_shape=["book_id", "details.visual_purpose"], evidence="bookforge.query.visual:get_visual_action_readiness", process_area="visual_assets"),
]


DESIGNED_GAP_CAPABILITIES: List[CapabilityDescriptor] = [
    _gap_spec("gap.deep_state.inventory", "Deep state and inventory projection layer", unit_type="query", capability_type="gap", scopes=["book", "chapter", "section", "scene", "character"], selector_shape=["book_id"]),
    _gap_spec("gap.compile_export_quality", "Compile/export and reader quality gate surface", unit_type="macro_workflow", capability_type="gap", scopes=["book", "chapter"], selector_shape=["book_id"], mutation_class="diagnostic_only"),
    _gap_spec("gap.visual.reference_image_workflows", "Reference-image guided visual workflows", unit_type="primitive_action", capability_type="gap", scopes=["author", "character", "book", "scene"], selector_shape=["book_id", "details.reference_image_refs"], mutation_class="provisional_branch_mutation", process_area="visual_assets", details={"default_provider_model": "nano-banana"}),
    _gap_spec("gap.visual.compose_layers", "Compose visual layers from generated assets", unit_type="primitive_action", capability_type="gap", scopes=["book", "scene", "branch"], selector_shape=["book_id", "details.layer_manifest"], mutation_class="provisional_branch_mutation", process_area="visual_assets"),
]


def _observed_action_options(workspace: Path, book_id: str) -> Dict[str, Any]:
    observed: Dict[str, Any] = {}
    selectors = [
        ScopeSelector(book_id=book_id),
        ScopeSelector(book_id=book_id, chapter=1, section=1),
        ScopeSelector(book_id=book_id, chapter=1, scene=1),
        ScopeSelector(book_id=book_id, branch_id="__capability_projection_probe__"),
        ScopeSelector(book_id=book_id, branch_id="__capability_projection_probe__", chapter=1, scene=1),
        ScopeSelector(book_id=book_id, fork_group_id="__capability_projection_probe__"),
        ScopeSelector(book_id="__book_intents__", workflow_family="book_intent"),
    ]
    for selector in selectors:
        try:
            for option in list_execution_options(workspace, selector, prefer_emitted=False):
                observed.setdefault(option.action, option)
        except Exception:
            continue
    return observed


def _merge_observed_action_spec(spec: CapabilityDescriptor, option: Any) -> CapabilityDescriptor:
    if option is None:
        return spec
    details = dict(spec.details)
    if option.workflow_family and "workflow_family" not in details:
        details["workflow_family"] = option.workflow_family
    details["observed_from_execution_option"] = True
    return CapabilityDescriptor(
        capability_id=spec.capability_id,
        human_label=option.summary or spec.human_label,
        unit_type=spec.unit_type,
        capability_type=spec.capability_type,
        implementation_status=spec.implementation_status,
        action_key=spec.action_key,
        query_key=spec.query_key,
        supported_scope_kinds=list(spec.supported_scope_kinds),
        required_selector_shape=list(option.selector_requirements or spec.required_selector_shape),
        branch_policy=option.branch_policy or spec.branch_policy,
        mutation_class=spec.mutation_class,
        approval_required=spec.approval_required,
        readiness_source=spec.readiness_source,
        expected_receipt_type=spec.expected_receipt_type,
        process_area=spec.process_area,
        produced_artifact_statuses=list(spec.produced_artifact_statuses),
        legal_next_action_relationships=list(spec.legal_next_action_relationships),
        refusal_semantics=spec.refusal_semantics,
        child_actions=list(spec.child_actions),
        evidence_sources=list(spec.evidence_sources),
        details=details,
    )


def get_capability_projection(workspace: Optional[Path | str] = None, book_id: Optional[str] = None) -> CapabilityProjection:
    observed: Dict[str, Any] = {}
    projection_source = "static_registry"
    if workspace is not None and book_id:
        observed = _observed_action_options(Path(workspace), str(book_id))
        if observed:
            projection_source = "static_registry+execution_options"

    capabilities: List[CapabilityDescriptor] = []
    for action_key in sorted(ACTION_CAPABILITY_SPECS):
        capabilities.append(_merge_observed_action_spec(ACTION_CAPABILITY_SPECS[action_key], observed.get(action_key)))
    capabilities.extend(QUERY_CAPABILITY_SPECS)
    capabilities.extend(READINESS_CAPABILITY_SPECS)
    capabilities.extend(DESIGNED_GAP_CAPABILITIES)
    scope_kinds = sorted({scope for capability in capabilities for scope in capability.supported_scope_kinds})
    process_areas = sorted({capability.process_area for capability in capabilities if capability.process_area})
    return CapabilityProjection(
        capabilities=capabilities,
        projection_source=projection_source,
        details={
            "static_action_count": len(ACTION_CAPABILITY_SPECS),
            "observed_action_count": len(observed),
            "unprojected_observed_actions": sorted(set(observed) - set(ACTION_CAPABILITY_SPECS)),
            "query_count": len(QUERY_CAPABILITY_SPECS),
            "readiness_count": len(READINESS_CAPABILITY_SPECS),
            "designed_gap_count": len(DESIGNED_GAP_CAPABILITIES),
            "scope_kinds": scope_kinds,
            "process_areas": process_areas,
            "static_dynamic_boundary": "Capability descriptors are static. Use readiness and legal-next-action queries for a selected scope.",
        },
    )
